name: Generate Flood Map

on:
  schedule:
    - cron: '0 2,6,10,14,18,22 * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Add ubuntugis-unstable PPA
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
      - name: Install GDAL system dependencies
        run: sudo apt-get install -y gdal-bin libgdal-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run Python script
        run: python flood.py

      - name: Configure Git
        run: |
          git config --global user.name "jpppamintuan"
          git config --global user.email "jpppamintuan@gmail.com"
          
      - name: Commit and Push
        if: success()
        run: |
          git add flood.html
          git add gfamap_new.png
          git commit -m "Update flood.html and gfamap_new.png"
          git push
